Repository DeltaHelpDesk/helpdesk, pull requests merged in 2019-12, with the labels that each got.

#201 Login menu enhancement
  fe/components/Login/Login.tsx
  fe/components/Login/MicrosoftButtonLogin.tsx
  fe/tslint.json
Labels: enhancement

#202 Improvements, CustomCard added
  fe/components/TaskBoard/TaskBoard.tsx
Labels: enhancement, fix

#203 Client config
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.graphql
  backend/src/auth/auth.resolvers.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/user.entity.ts
  backend/src/clientConfig/clientConfig.graphql
  backend/src/clientConfig/clientConfig.module.ts
  backend/src/clientConfig/clientConfig.resolvers.ts
  backend/src/clientConfig/clientConfig.type.ts
  backend/src/gql.ts
  backend/src/main.ts
  backend/yarn.lock
Labels: enhancement

#206 Menu icon alignment
  fe/components/MainAppBar/UserLogged.tsx
Labels: fix

#207 React import(s) FIX
  README.md
  fe/components/Administration/NewUser/NewUser.tsx
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/AuthenticatedRoute.tsx
  fe/components/DarkModeSelect/DarkModeSelect.tsx
  fe/components/Dates/DatePicker.tsx
  fe/components/Errors/Kaomoji.tsx
  fe/components/Footer copy/Footer.tsx
  fe/components/Footer/Footer.tsx
  fe/components/LanguageSelect/LanguageSelect.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/NewTask/NewTask.tsx
  fe/components/ScrollTop/ScrollTop.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskDetail/DetailForm.tsx
  fe/components/TaskDetail/LogsTable.tsx
  fe/components/Themes/ThemeProvider.tsx
  fe/pages/_document.tsx
  fe/pages/about.tsx
  fe/pages/board.tsx
  fe/pages/index.tsx
  fe/pages/login.tsx
  fe/pages/new.tsx
  fe/src/Router.tsx
Labels: fix

#208 Task list
  flutter/helpdesk_mobile/.flutter-plugins-dependencies
  flutter/helpdesk_mobile/.gitignore
  flutter/helpdesk_mobile/android/gradle.properties
  flutter/helpdesk_mobile/lib/main.dart
  flutter/helpdesk_mobile/lib/src/app.dart
  flutter/helpdesk_mobile/lib/src/models/enums.dart
  flutter/helpdesk_mobile/lib/src/models/logType.dart
  flutter/helpdesk_mobile/lib/src/models/query.dart
  flutter/helpdesk_mobile/lib/src/models/taskType.dart
  flutter/helpdesk_mobile/lib/src/ui/components/taskList/sections.dart
  flutter/helpdesk_mobile/lib/src/ui/components/taskList/taskCard.dart
  flutter/helpdesk_mobile/lib/src/ui/pages/tasklist.dart
Labels: enhancement

#213 Czech format
  fe/components/Dates/DateFormatter.tsx
Labels: enhancement

#218 Task comments & Subtasks
  backend/src/app.module.ts
  backend/src/auth/user.entity.ts
  backend/src/clientConfig/clientConfig.graphql
  backend/src/clientConfig/clientConfig.resolvers.ts
  backend/src/clientConfig/clientConfig.type.ts
  backend/src/common/defaults.ts
  backend/src/fakeData.service.ts
  backend/src/gql.ts
  backend/src/task/comment/comment.entity.ts
  backend/src/task/comment/comment.module.ts
  backend/src/task/comment/comment.resolvers.ts
  backend/src/task/comment/comment.service.ts
  backend/src/task/log/log.entity.ts
  backend/src/task/subtask/subtask.entity.ts
  backend/src/task/subtask/subtask.module.ts
  backend/src/task/subtask/subtask.resolvers.ts
  backend/src/task/subtask/subtask.service.ts
  backend/src/task/task.entity.ts
  backend/src/task/task.graphql
  backend/src/task/task.module.ts
  backend/src/task/task.resolvers.ts
  backend/src/task/task.service.ts
Labels: enhancement

#219 Backend CI
  README.md
  backend/package.json
  backend/yarn.lock
Labels: enhancement, fix

#220 Update Semaphore configuration
  .circleci/config.yml
  .semaphore/semaphore.yml
  README.md
Labels: enhancement, fix

#221 Christmas time added
  fe/components/MainAppBar/Logo/Logo.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/Snow/Snow.tsx
  fe/components/Snow/SnowComponent.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/public/static/logos/christmas_logo.png
  fe/public/static/logos/logo_new.png
  fe/utils/dateHelper.ts
  fe/yarn.lock
  flutter/helpdesk_mobile/pubspec.lock
Labels: enhancement

#222 Dependencies update
  backend/yarn.lock
  fe/components/MainAppBar/Logo/Logo.tsx
  fe/components/Snow/Snow.tsx
  fe/package.json
  fe/utils/TextHelper.ts
  fe/utils/cookieHelper.ts
  fe/utils/dateHelper.ts
  fe/yarn.lock
Labels: fix

#224 Role icon added
  fe/components/Administration/UserList/User.tsx
  fe/components/RoleIcon/RoleIcon.tsx
Labels: enhancement

#226 Fix
  fe/components/RoleIcon/RoleIcon.tsx
  fe/components/ScrollTop/ScrollTop.tsx
  fe/utils/dateHelper.ts
Labels: fix

#227 Hotfix/localization
  README.md
  backend/src/localization/localization.service.ts
  backend/src/localization/localizations/cs/translations.json
Labels: fix

#228 Task detail v1.0
  README.md
  fe/components/MainAppBar/UserLogged.tsx
  fe/components/TaskBoard/AddComment.tsx
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/CommentsContainer.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskComment.tsx
  fe/components/TaskBoard/TaskDetail.tsx
  fe/public/static/static.css
  fe/src/graphql/graphql-schema.json
  fe/src/graphql/mutations.ts
  fe/src/graphql/queries.ts
  fe/src/graphql/types/AddComment.ts
  fe/src/graphql/types/DeleteComment.ts
  fe/src/graphql/types/GetTaskComments.ts
  fe/src/graphql/types/GetTaskDetail.ts
  fe/src/graphql/types/addTask.ts
  fe/src/graphql/types/changeTaskBoardState.ts
  fe/src/graphql/types/getTask.ts
  fe/src/graphql/types/getTasks.ts
Labels: enhancement

#229 Favicon added
  fe/components/Layouts/HeadComponent.tsx
  fe/public/static/images/favicon/android-chrome-192x192.png
  fe/public/static/images/favicon/android-chrome-512x512.png
  fe/public/static/images/favicon/apple-touch-icon.png
  fe/public/static/images/favicon/browserconfig.xml
  fe/public/static/images/favicon/favicon-16x16.png
  fe/public/static/images/favicon/favicon-32x32.png
  fe/public/static/images/favicon/favicon.ico
  fe/public/static/images/favicon/mstile-144x144.png
  fe/public/static/images/favicon/mstile-150x150.png
  fe/public/static/images/favicon/mstile-310x150.png
  fe/public/static/images/favicon/mstile-310x310.png
  fe/public/static/images/favicon/mstile-70x70.png
  fe/public/static/images/favicon/safari-pinned-tab.svg
  fe/public/static/images/favicon/site.webmanifest
Labels: enhancement

#230 Sharing head component added
  fe/components/Sharing/SharingHead/SharingHead.tsx
  fe/pages/index.tsx
Labels: enhancement

#231 // in ImageUrl fixed
  fe/components/Sharing/SharingHead/SharingHead.tsx
Labels: fix

#232 Hi-res favicon added
  fe/components/Sharing/SharingHead/SharingHead.tsx
  fe/public/static/images/favicon/maxresdefault.png
Labels: fix

#234 Mutation Fix
  backend/src/task/task.service.ts
Labels: fix

#235 Layout updated
  fe/components/TaskBoard/BoardContainer.tsx
Labels: enhancement, fix

#236 Component added
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/TaskBoard/AddComment.tsx
  fe/components/TaskBoard/TaskActions.tsx
  fe/components/TaskBoard/TaskDetail.tsx
Labels: enhancement

#237 Page re-make
  fe/components/AdminSelect/AdminSelect.tsx
  fe/components/NewTask/NewTaskContainer.tsx
  fe/pages/new.tsx
  fe/utils/TextHelper.ts
Labels: enhancement

#239 Dependencies & ReadME update
  README.md
  backend/README.md
  backend/src/localization/localizations/cs/translations.json
  backend/yarn.lock
  fe/README.md
  fe/src/graphql/client.ts
  fe/yarn.lock
Labels: fix
