Repository DeltaHelpDesk/helpdesk, pull requests merged in 2019-09, with the labels that each got.

#105 DateFormatter completion
  frontend/src/components/Administration/UserList/User.tsx
  frontend/src/components/Dates/DateFormatter.tsx
  frontend/src/components/Dates/DatePicker.tsx
  package.json
Labels: enhancement

#107 Fix yarn.lock for backend
  backend/yarn.lock
Labels: bug

#108 Login button fixed
  frontend/src/components/Homepage/HomePage.tsx
Labels: bug

#109 Logged User custom component added
  frontend/src/components/Menu/Menu.tsx
  frontend/src/components/Menu/UserLogged.tsx
  frontend/src/utils/TextHelper.tsx
Labels: enhancement

#110 Login on enter key added
  frontend/src/components/Login/Login.tsx
Labels: enhancement

#113 Logout fixed
  frontend/src/graphql/auth.tsx
Labels: bug

#114 More translations
  backend/src/localization/localizations/cs/translations.json
Labels: enhancement

#115 Opravení nechtěného odhlašování
  backend/src/auth/auth.graphql
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.resolvers.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/authType.enum.ts
  backend/src/auth/jwtPayload.interface.ts
  backend/src/auth/loginToken.entity.ts
  backend/src/auth/user.entity.ts
  backend/src/fakeData.service.ts
  backend/src/gql.ts
Labels: bug

#116 Logout FIX
  frontend/src/graphql/auth.tsx
  frontend/src/graphql/client.ts
Labels: bug

#117 Removed docker for frontend
  docker-compose.prod.yml
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: bug

#119 Permissions fix
  backend/src/auth/auth.resolvers.ts
Labels: bug

#120 Microsoft login FIX
  backend/src/auth/auth.service.ts
  backend/src/auth/loginToken.entity.ts
Labels: bug

#122 Login token FIX
  backend/src/auth/loginToken.entity.ts
Labels: bug

#125 Get first letters fixed
  frontend/src/utils/TextHelper.tsx
Labels: bug

#123 Token expiration
  backend/local.env-example
  backend/prod.env
  backend/remote.env
  backend/src/app.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/loginToken.entity.ts
  backend/src/autoJob/DTOs/LoginDto.ts
  backend/src/autoJob/autojob.controller.ts
  backend/src/autoJob/autojob.module.ts
  backend/src/autoJob/autojob.services.ts
  backend/src/config/config.module.ts
  backend/src/config/config.service.ts
Labels: enhancement

#126 Production database
  backend/prod.env
Labels: enhancement

#128 Datepicker merge
  frontend/package.json
  frontend/src/components/Dates/DateFormatter.tsx
Labels: bug

#129 UserList dateformatter implementation
  frontend/src/components/Administration/UserList/User.tsx
  frontend/src/components/Dates/DateFormatter.tsx
Labels: enhancement

#133 Menu position fixed
  frontend/src/Layout/Layout.tsx
  frontend/src/components/Menu/Menu.tsx
Labels: bug

#134 Menu design merge to dev
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Menu/Menu.tsx
  frontend/src/components/Menu/logo_new.png
  frontend/src/theme.ts
Labels: enhancement

#135 Merge board into dev
  frontend/src/Router.tsx
  frontend/src/components/TaskBoard/TaskBoard.tsx
  frontend/src/components/TaskBoard/TaskCard.tsx
  frontend/src/components/TaskList/TaskList.tsx
  frontend/src/components/TaskList/TaskListQueries.ts
Labels: enhancement

#131 NestJS 6
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/filterOnRoleOrUser.interceptor.ts
  backend/src/auth/user.request.decorator.ts
  backend/src/gql.ts
  backend/src/task/task.module.ts
  backend/yarn.lock
Labels: enhancement

#136 NestJS - Quick FIX
  backend/src/app.module.ts
Labels: fix

#137 Types added
  frontend/src/graphql/types.ts
Labels: fix
