Repository DeltaHelpDesk/helpdesk, pull requests merged in 2019-11, with the labels that each got.

#171 Toast FIX
  fe/pages/_app.tsx
Labels: fix

#172 Styles FIX
  fe/pages/_app.tsx
  fe/pages/_document.tsx
  fe/src/theme.ts
Labels: fix

#173 Update
  fe/package.json
  fe/yarn.lock
Labels: fix

#174 Backend - External login + Update
  backend/src/auth/auth.graphql
  backend/src/auth/auth.resolvers.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/authType.enum.ts
  backend/src/gql.ts
  backend/yarn.lock
Labels: enhancement, fix

#175 Backend FIX
  backend/package.json
  backend/production.env
Labels: fix

#176 GraphQL - Debug
  backend/src/app.module.ts
Labels: fix

#177 GraphQL type autogen added
  fe/codegen.yml
  fe/components/TaskBoard/TaskBoard.tsx
  fe/package.json
  fe/src/graphql/types.tsx
  fe/yarn.lock
Labels: enhancement

#179 Added Google login
  fe/components/Login/Login.tsx
  fe/components/Login/SocialButton.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/src/auth/authWrapper.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/types.tsx
  fe/tslint.json
  fe/types/react-social-login/index.d.ts
  fe/types/react-toast-notifications/index.d.ts
  fe/yarn.lock
Labels: enhancement, fix

#180 Theme Provider
  fe/components/Administration/Administration.tsx
  fe/components/DarkModeSelect/DarkModeSelect.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/LanguageSelect/LanguageSelect.tsx
  fe/components/Layouts/HeadComponent.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/Themes/MainTheme.ts
  fe/components/Themes/ThemeProvider.tsx
  fe/pages/_app.tsx
  fe/pages/_error.tsx
  fe/pages/settings.tsx
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/utils/cookieHelper.ts
Labels: enhancement, fix

#181 NextJS - Social login
  fe/components/Administration/Administration.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/Login/Login.tsx
  fe/components/Login/MicrosoftButtonLogin.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/Themes/ThemeProvider.tsx
  fe/pages/_error.tsx
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/src/graphql/auth.tsx
  fe/src/services/microsoft.js
  fe/src/services/microsoft.ts
Labels: enhancement

#182 Added Backgorund Image as a component
  fe/components/Administration/Administration.tsx
  fe/components/Background/Background.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/Login/Login.tsx
Labels: enhancement

#185 Removed demo pages
  fe/Procfile
  fe/components/Dates/DatePicker.tsx
  fe/components/List.tsx
  fe/components/ListDetail.tsx
  fe/components/ListItem.tsx
  fe/interfaces/index.ts
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/detail.tsx
  fe/pages/initial-props.tsx
  fe/utils/sample-api.ts
  fe/yarn.lock
Labels: fix

#186 Login FIX
  fe/components/Login/Login.tsx
  fe/package.json
  fe/yarn.lock
Labels: fix

#187 FB Login FIX
  fe/components/Login/Login.tsx
  fe/package.json
  fe/yarn.lock
Labels: fix

#190 Added ScrollTop component
  fe/components/ScrollTop/ScrollTop.tsx
  fe/pages/_app.tsx
Labels: enhancement

#191 Revert "Added ScrollTop component"
  fe/components/ScrollTop/ScrollTop.tsx
  fe/pages/_app.tsx
Labels: fix

#194 Typegen added
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/Background/Background.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/generated/schema.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/admin/users.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/graphql-global-types.ts
  fe/src/graphql/graphql-schema.json
  fe/src/graphql/mutations.ts
  fe/src/graphql/queries.ts
  fe/src/graphql/types/addTask.ts
  fe/src/graphql/types/changeTaskState.ts
  fe/src/graphql/types/createUserEmail.ts
  fe/src/graphql/types/deleteTask.ts
  fe/src/graphql/types/getAdmins.ts
  fe/src/graphql/types/getSession.ts
  fe/src/graphql/types/getTask.ts
  fe/src/graphql/types/getTasks.ts
  fe/src/graphql/types/getUsers.ts
  fe/src/graphql/types/removeUser.ts
  fe/yarn.lock
Labels: enhancement

#195 Login better buttons
  fe/components/Administration/Administration.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
Labels: enhancement

#196 Code refactored
  fe/src/graphql/auth.tsx
  fe/src/graphql/graphql-global-types.ts
  fe/src/graphql/mutations.ts
  fe/src/graphql/queries.ts
  fe/src/graphql/types/loginEmail.ts
  fe/src/graphql/types/loginExternal.ts
  fe/src/graphql/types/loginOffice.ts
  fe/src/graphql/types/logout.ts
Labels: bug, fix

#197 Trello
  fe/components/Administration/UserList/User.tsx
  fe/components/Dates/DateFormatter.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskCard.tsx
  fe/package.json
  fe/pages/board.tsx
  fe/src/graphql/mutations.ts
  fe/src/graphql/types/changeTaskBoardState.ts
  fe/yarn.lock
  frontend/src/components/TaskBoard/TaskBoard.tsx
Labels: enhancement

#199 Scroll Top
  fe/components/ScrollTop/ScrollTop.tsx
  fe/pages/_app.tsx
  fe/yarn.lock
Labels: enhancement

#200 Feature/CI
  .gitignore
  README.md
Labels: enhancement, fix
