Repository DeltaHelpDesk/helpdesk, pull requests merged in 2019-10, with the labels that each got.

#139 Merge models usage to dev
  frontend/src/components/TaskBoard/TaskBoard.tsx
  frontend/src/components/TaskBoard/TaskCard.tsx
  frontend/src/components/TaskDetail/Log.tsx
  frontend/src/components/TaskDetail/LogsTable.tsx
  frontend/src/components/TaskList/Task.tsx
  frontend/src/components/TaskList/TaskList.tsx
Labels: fix

#142 Merge new NextJS project into dev
  fe/.gitignore
  fe/README.md
  fe/components/Layout.tsx
  fe/components/List.tsx
  fe/components/ListDetail.tsx
  fe/components/ListItem.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/interfaces/index.ts
  fe/next-env.d.ts
  fe/package.json
  fe/pages/about.tsx
  fe/pages/detail.tsx
  fe/pages/index.tsx
  fe/pages/initial-props.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/client.ts
  fe/src/graphql/resolvers.js
  fe/src/graphql/typedefs.js
  fe/src/graphql/types.ts
  fe/tsconfig.json
  fe/utils/sample-api.ts
  fe/yarn.lock
Labels: enhancement

#141 DayPicker completed & DateFormatter implemented
  frontend/package.json
  frontend/src/components/Dates/DatePicker.tsx
  frontend/src/components/Dates/DayPicker.tsx
  frontend/src/components/TaskDetail/LogsTable.tsx
  frontend/src/components/TaskDetail/TaskDetail.tsx
Labels: enhancement

#144 Main ReadMe update
  README.md
Labels: fix

#146 Added roleView
  frontend/public/image_admin.svg
  frontend/public/image_superadmin.svg
  frontend/public/image_user.svg
  frontend/src/components/Administration/UserList/User.tsx
  frontend/src/components/RoleView/RoleView.tsx
  frontend/yarn.lock
Labels: enhancement

#148 Backend update
  backend/package.json
  backend/yarn.lock
Labels: fix

#150 NextJS branch
  .gitignore
  fe/components/About/About.tsx
  fe/components/Administration/Administration.tsx
  fe/components/Administration/AdministrationContainer.tsx
  fe/components/Administration/NewUser/NewUser.tsx
  fe/components/Administration/NewUser/NewUserQueries.ts
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/Administration/UserList/UserListQueries.ts
  fe/components/AuthenticatedRoute.tsx
  fe/components/Dates/DateFormatter.tsx
  fe/components/Dates/DatePicker.tsx
  fe/components/Footer copy/Footer.tsx
  fe/components/Footer/Footer.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/Loading/Loading.tsx
  fe/components/Login/Login.tsx
  fe/components/Login/MicrosoftButtonLogin.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/NewTask/NewTask.tsx
  fe/components/NewTask/NewTaskQueries.ts
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskCard.tsx
  fe/components/TaskDetail/DetailForm.tsx
  fe/components/TaskDetail/Log.tsx
  fe/components/TaskDetail/LogsTable.tsx
  fe/components/TaskDetail/TaskDetail.tsx
  fe/components/TaskDetail/TaskDetailQueries.ts
  fe/components/TaskList/Task.tsx
  fe/components/TaskList/TaskList.tsx
  fe/components/TaskList/TaskListQueries.ts
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/about.tsx
  fe/pages/index.tsx
  fe/src/Global/Keys.ts
  fe/src/Router.tsx
  fe/src/Routes.ts
  fe/src/graphql/auth.tsx
  fe/src/graphql/client.ts
  fe/src/services/microsoft.js
  fe/tsconfig.json
  fe/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#151 Head updated
  fe/components/Layouts/Layout.tsx
  fe/static/bootstrap.css
  fe/static/mdb.css
  fe/static/static.css
Labels: enhancement

#152 Board page added
  fe/components/MainAppBar/MainAppBar.tsx
  fe/pages/board.tsx
Labels: enhancement

#153 Link component added
  fe/components/Layouts/Layout.tsx
  fe/components/LinkComponents/LinkComponent.tsx
Labels: enhancement

#154 NextJS login
  fe/components/Homepage/HomePage.tsx
  fe/components/Login/Login.tsx
  fe/pages/_app.tsx
  fe/pages/login.tsx
  fe/src/graphql/auth.tsx
Labels: enhancement, fix

#156 Added Ts-Lint
  fe/package.json
  fe/tslint.json
  fe/yarn.lock
Labels: enhancement

#157 Autorizace
  fe/components/Login/Login.tsx
  fe/pages/_app.tsx
  fe/pages/board.tsx
  fe/src/Routes.ts
  fe/src/graphql/auth.tsx
Labels: enhancement

#158 Feature/image change
  frontend/src/about/faltji/image.png
  frontend/src/about/faltji/index.ts
  frontend/src/about/index.ts
  frontend/src/about/stermi/image.jpg
  frontend/src/about/stermi/index.ts
Labels: enhancement

#161 Page - User roles
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/TaskBoard/TaskCard.tsx
  fe/pages/board.tsx
  fe/pages/index.tsx
  fe/src/Routes.ts
  fe/src/graphql/auth.tsx
Labels: enhancement

#163 Toasts & Refactor
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/NewTask/NewTask.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/board.tsx
  fe/pages/index.tsx
  fe/pages/new.tsx
  fe/src/auth/authWrapper.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/client.ts
  fe/yarn.lock
Labels: enhancement, fix

#164 Pages added
  fe/components/Administration/Administration.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/Loading/Loading.tsx
  fe/components/TaskList/TaskList.tsx
  fe/pages/admin/index.tsx
  fe/pages/admin/users.tsx
  fe/pages/settings.tsx
  fe/src/Routes.ts
  frontend/yarn.lock
Labels: fix

#165 Refactor & Auth
  fe/components/Administration/Administration.tsx
  fe/components/Administration/AdministrationContainer.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/pages/admin/index.tsx
  fe/pages/admin/users.tsx
Labels: enhancement, fix

#167 Kaomoji added
  fe/components/Errors/Kaomoji.tsx
  fe/pages/_error.tsx
Labels: enhancement

#168 Code refactor - TS lint
  fe/components/Administration/Administration.tsx
  fe/components/Administration/NewUser/NewUser.tsx
  fe/components/Administration/NewUser/NewUserQueries.ts
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserListQueries.ts
  fe/components/AuthenticatedRoute.tsx
  fe/components/Dates/DateFormatter.tsx
  fe/components/Dates/DatePicker.tsx
  fe/components/Errors/Kaomoji.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/Layouts/HeadComponent.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/LinkComponents/LinkComponent.tsx
  fe/components/List.tsx
  fe/components/ListDetail.tsx
  fe/components/ListItem.tsx
  fe/components/Loading/Loading.tsx
  fe/components/Login/Login.tsx
  fe/components/Login/MicrosoftButtonLogin.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/MainAppBar/UserLogged.tsx
  fe/components/NewTask/NewTaskQueries.ts
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskCard.tsx
  fe/components/TaskDetail/DetailForm.tsx
  fe/components/TaskDetail/Log.tsx
  fe/components/TaskDetail/LogsTable.tsx
  fe/components/TaskDetail/TaskDetail.tsx
  fe/components/TaskDetail/TaskDetailQueries.ts
  fe/components/TaskList/Task.tsx
  fe/components/TaskList/TaskList.tsx
  fe/components/TaskList/TaskListQueries.ts
  fe/interfaces/index.ts
  fe/pages/_app.tsx
  fe/pages/_error.tsx
  fe/pages/about.tsx
  fe/pages/detail.tsx
  fe/pages/login.tsx
  fe/pages/settings.tsx
  fe/src/Global/Keys.ts
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/src/Router.tsx
  fe/src/Routes.ts
  fe/utils/TextHelper.ts
  fe/utils/sample-api.ts
Labels: fix

#169 Toasts & Lint FIX
  .gitignore
  fe/components/About/About.tsx
  fe/components/Footer copy/Footer.tsx
  fe/components/Footer/Footer.tsx
  fe/components/Login/Login.tsx
  fe/components/NewTask/NewTask.tsx
  fe/components/NewTask/NewTaskQueries.ts
  fe/components/TaskDetail/TaskDetailQueries.ts
  fe/pages/initial-props.tsx
  fe/pages/login.tsx
  fe/src/auth/authWrapper.tsx
  fe/tsconfig.json
  fe/types/react-toast-notifications/index.d.ts
Labels: fix
