Repository DeltaHelpDesk/helpdesk, pull requests merged in 2020-02, with the labels that each got.

#272 Localization
  backend/src/localization/localizations/cs/translations.json
  fe/components/AdminSelect/AdminSelect.tsx
  fe/components/Administration/AdminContainer/AdminContainer.tsx
  fe/components/Administration/UserList/DeleteUser.tsx
  fe/components/Administration/UserList/EditUser.tsx
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/DarkModeSelect/DarkModeSelect.tsx
  fe/components/Dates/DateFormatter.tsx
  fe/components/Login/TipBar.tsx
  fe/components/MainAppBar/UserLogged.tsx
  fe/components/NewTask/NewTaskContainer.tsx
  fe/components/RoleIcon/RoleIcon.tsx
  fe/components/RoleSelect/RoleSelect.tsx
  fe/components/TaskBoard/AddComment.tsx
  fe/components/TaskBoard/CommentsContainer.tsx
  fe/components/TaskBoard/TaskActions.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskComment.tsx
  fe/components/TaskBoard/TaskDetail.tsx
  fe/pages/_error.tsx
  fe/pages/login.tsx
  fe/pages/settings.tsx
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/src/Locales/LocalizationKeys.ts
  fe/yarn.lock
Labels: enhancement, fix

#274 Localization 2.0
  backend/src/localization/localizations/cs/translations.json
  backend/src/localization/localizations/en/translations.json
  fe/components/DarkModeSelect/DarkModeSelect.tsx
  fe/components/LanguageSelect/LanguageSelect.tsx
  fe/components/Login/Login.tsx
  fe/components/Login/MicrosoftButtonLogin.tsx
  fe/package.json
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/src/Locales/LocalizationKeys.ts
  fe/src/graphql/graphql-schema.json
  fe/src/graphql/mutations.ts
  fe/src/graphql/queries.ts
  fe/src/graphql/types/EditUser.ts
  fe/src/graphql/types/EditUserLanguage.ts
  fe/src/graphql/types/getSession.ts
  fe/src/graphql/types/loginEmail.ts
  fe/src/graphql/types/loginExternal.ts
  fe/src/graphql/types/loginOffice.ts
  fe/yarn.lock
Labels: enhancement, fix

#275 Packages update
  backend/yarn.lock
  fe/yarn.lock
Labels: fix

#276 Ratio changed
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/TaskDetail.tsx
Labels: enhancement

#278 FIX
  fe/components/TaskBoard/TaskBoard.tsx
Labels: fix

#281 Fix
  fe/src/graphql/mutations.ts
  fe/yarn.lock
Labels: fix

#282 Dialogy
  fe/components/Login/Login.tsx
Labels: enhancement, fix
