Repository DeltaHelpDesk/helpdesk, pull requests merged in 2020-01, with the labels that each got.

#241 FE - Localization preparation
  backend/src/localization/localizations/cs/translations.json
  fe/components/Homepage/HomePage.tsx
  fe/components/Layouts/Layout.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/NewTask/NewTaskContainer.tsx
  fe/components/Sharing/SharingHead/SharingHead.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/new.tsx
  fe/src/Locales/Lang/Czech.ts
  fe/src/Locales/Lang/English.ts
  fe/src/Locales/Localisations.ts
  fe/src/Locales/LocalizationKeys.ts
  fe/src/auth/authWrapper.tsx
  fe/src/graphql/auth.tsx
  fe/src/i18n.ts
  fe/utils/dateHelper.ts
  fe/yarn.lock
Labels: enhancement, fix

#242 Localization & Auth FIX
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/Login/Login.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/TaskDetail/DetailForm.tsx
  fe/components/TaskDetail/LogsTable.tsx
  fe/components/TaskDetail/TaskDetail.tsx
  fe/components/TaskList/Task.tsx
  fe/components/TaskList/TaskList.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/admin/index.tsx
  fe/pages/board.tsx
  fe/src/auth/authWrapper.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/types.tsx
  fe/yarn.lock
Labels: fix

#243 Fyks
  fe/components/Login/Login.tsx
Labels: fix

#244 Merge styles to dev
  fe/components/Administration/UserList/UserListContainer.tsx
  fe/components/Login/Login.tsx
  fe/components/NewTask/NewTaskContainer.tsx
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/TaskBoard.tsx
Labels: enhancement

#245 Trello link
  README.md
Labels: enhancement

#246 Styles updated
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/CommentsContainer.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskComment.tsx
  fe/components/TaskBoard/TaskDetail.tsx
Labels: enhancement

#247 User Edit
  fe/components/Administration/UserList/DeleteUser.tsx
  fe/components/Administration/UserList/EditUser.tsx
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/Homepage/HomePage.tsx
  fe/components/RoleSelect/RoleSelect.tsx
  fe/package.json
  fe/pages/_app.tsx
  fe/public/static/static.css
  fe/src/graphql/mutations.ts
  fe/src/graphql/types/EditUserAdmin.ts
  fe/yarn.lock
Labels: enhancement

#252 Removed unused components
  fe/components/About/About.tsx
  fe/components/AdminSelect/AdminSelect.tsx
  fe/components/Administration/AdminContainer/AdminContainer.tsx
  fe/components/Administration/Administration.tsx
  fe/components/Administration/AdministrationContainer.tsx
  fe/components/Administration/NewUser/NewUser.tsx
  fe/components/Administration/NewUser/NewUserQueries.ts
  fe/components/Administration/UserList/DeleteUser.tsx
  fe/components/Administration/UserList/EditUser.tsx
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserListQueries.ts
  fe/components/AuthenticatedRoute.tsx
  fe/components/Footer copy/Footer.tsx
  fe/components/Footer/Footer.tsx
  fe/components/NewTask/NewTask.tsx
  fe/components/NewTask/NewTaskQueries.ts
  fe/components/RoleIcon/RoleIcon.tsx
  fe/components/RoleSelect/RoleSelect.tsx
  fe/components/TaskBoard/AddComment.tsx
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/CommentsContainer.tsx
  fe/components/TaskBoard/TaskActions.tsx
  fe/components/TaskBoard/TaskComment.tsx
  fe/components/TaskBoard/TaskDetail.tsx
  fe/components/TaskDetail/DetailForm.tsx
  fe/components/TaskDetail/LogsTable.tsx
  fe/components/TaskDetail/TaskDetail.tsx
  fe/components/TaskDetail/TaskDetailQueries.ts
  fe/components/TaskList/Task.tsx
  fe/components/TaskList/TaskList.tsx
  fe/components/TaskList/TaskListQueries.ts
  fe/src/Router.tsx
  package.json
  yarn.lock
Labels: fix

#253 Removed Logs
  .gitignore
  backend/src/app.module.ts
  backend/src/fakeData.service.ts
  backend/src/gql.ts
  backend/src/task/log/log.entity.ts
  backend/src/task/task.entity.ts
  backend/src/task/task.graphql
  backend/src/task/task.module.ts
  backend/src/task/task.resolvers.ts
  backend/src/task/task.service.ts
  backend/yarn.lock
  fe/components/TaskBoard/TaskBoard.tsx
  fe/src/graphql/graphql-schema.json
  fe/src/graphql/queries.ts
  fe/src/graphql/types/getTask.ts
Labels: fix

#256 Task urls added
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskDetail.tsx
  fe/pages/admin/index.tsx
  fe/pages/board.tsx
Labels: enhancement

#257 Sorting added
  fe/components/TaskBoard/TaskBoard.tsx
Labels: enhancement

#258 Auth FIX
  fe/components/Administration/AdminContainer/AdminContainer.tsx
  fe/components/Administration/UserList/User.tsx
  fe/components/Administration/UserList/UserList.tsx
  fe/components/MainAppBar/MainAppBar.tsx
  fe/components/TaskBoard/BoardContainer.tsx
  fe/components/TaskBoard/TaskBoard.tsx
  fe/components/TaskBoard/TaskDetail.tsx
  fe/pages/admin/index.tsx
  fe/src/graphql/auth.tsx
Labels: fix

#259 User deactivation
  .semaphore/semaphore.yml
  backend/src/auth/auth.graphql
  backend/src/auth/auth.resolvers.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/user.entity.ts
  backend/src/gql.ts
  fe/src/graphql/graphql-schema.json
  fe/src/graphql/queries.ts
  fe/src/graphql/types/getUsers.ts
  fe/yarn.lock
Labels: fix

#260 LoginTips
  fe/components/Errors/Kaomoji.tsx
  fe/components/Login/Login.tsx
  fe/components/Login/TipBar.tsx
Labels: enhancement

#261 Removed bootstrap
  fe/public/static/bootstrap.css
  fe/public/static/mdb.css
Labels: fix

#262 Task URL edit
  fe/components/NewTask/NewTaskContainer.tsx
  fe/pages/settings.tsx
Labels: fix

#265 Theme preference update
  fe/components/DarkModeSelect/DarkModeSelect.tsx
  fe/components/Login/Login.tsx
  fe/src/graphql/auth.tsx
  fe/src/graphql/mutations.ts
Labels: enhancement

#268 Ticket deactivation
  backend/src/auth/auth.graphql
  backend/src/auth/auth.resolvers.ts
  backend/src/auth/auth.service.ts
  backend/src/fakeData.service.ts
  backend/src/gql.ts
  backend/src/task/task.entity.ts
  backend/src/task/task.graphql
  backend/src/task/task.resolvers.ts
  backend/src/task/task.service.ts
Labels: enhancement

#271 BE - Task remove
  backend/src/task/task.resolvers.ts
  backend/src/task/task.service.ts
Labels: fix
